site_name: Epicurus Productions
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: static/logo.png
  favicon: static/logo.png
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  
  # Navigation
  nav:
  - Section:
    - Home: docs/index.md
    - New Page: docs/2-new-page.md
  #  - Monitoring Collector Network: docs/3-monitoring-collector-network.md
  #  - Archieve Docs: docs/4-archieve.md
  #  - KVM: docs/7-kvm.md
  #  - Notes: docs/8-notes.md

  # Color Scheme for both light and dark thems
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: lime
extra:
  generator: false
markdown_extensions:
  - attr_list

# Extenstion for mermaid support
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
