site_name: Epicurus Productions
site_url: https://gamefreakcabe.github.io/
theme:
  name: material
  font:
    text: Acme
  logo: static/logo.jpeg
  faviconi: static/logo.jpeg
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    # test
    - navigation.indexes
    - navigation.sections
  language: en
  
  # Navigation
  nav:
    - Home: index.md
    - Stories:
      - stories/index.md
      - The Shadow One and the General: stories/shadow-general.md
      - The Spec Ops and the Healer: stories/specops-healer.md
      - The Convict and the Spy: stories/convict-spy.md
    - Credits: credits.md

  # Color Scheme for both light and dark theme
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode    
      primary: black
      accent: lime

#extra:
#  generator: false
markdown_extensions:
  - attr_list
  - md_in_html

# Extenstion for mermaid support
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

