site_name: Epicurus Productions
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Acme
  logo: static/logo.jpeg
  favicon: static/logo.jpeg
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  
  # Navigation
  nav:
  - Section:
    - Home: docs/index.md
    - New Page: docs/2-about.md
    - Credits: docs/999-credits.md

  # Color Scheme for both light and dark thems
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode    
      primary: black
      accent: lime
#extra:
#  generator: false
#markdown_extensions:
#  - attr_list

# Extenstion for mermaid support
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
