site_name: Epicurus Productions
site_url: https://gamefreakcabe.github.io/
theme:
  name: material
  font:
    text: Acme
  logo: /logo.jpeg
  favicon: static/logo.jpeg
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    # test
    - navigation.indexes
    - navigation.sections
  language: en
  
  # Navigation
  nav:
  - Section:
    - section/index.md
    - Home: docs/index.md
    - About: docs/2-about.md
    - Scions of Covenant: section/p1.md
    - Credits: docs/999-credits.md
    - Page1: soc/p1.md

  # Color Scheme for both light and dark thems
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode    
      primary: black
      accent: lime

#extra:
#  generator: false
markdown_extensions:
  - attr_list
  - md_in_html

# Extenstion for mermaid support
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

